nodeLinker: node-modules

npmScopes:
  mangrovedao:
    npmRegistryServer: "https://registry.npmjs.org/@mangrovedao"

npmRegistryServer: "https://registry.npmjs.org/@mangrovedao"
npmPublishRegistry: "https://registry.npmjs.org/@mangrovedao"
