nodeLinker: node-modules

npmScopes:
  mangrovedao:
    npmRegistryServer: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"
npmPublishRegistry: "https://registry.npmjs.org"
