name: Publish Package
on: 
  workflow_dispatch:
    inputs:
      revision:
        description: 'Revision'
        required: true
        default: 'prerelease'
        type: choice
        options:
        - prerelease
        - minor
        - major
        - patch
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Infos
      run: |
        echo "revision: $INPUT_REVISION"
        echo -e changelog: $INPUT_CHANGELOG
      env:
        INPUT_REVISION: ${{ inputs.revision }}
        INPUT_CHANGELOG: ${{ inputs.changelog }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Node Install
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}

    - name: create .yarnrc
      run: |
        echo "npmRegistryServer: \"https://registry.npmjs.org\"" > .yarnrc.yml
        echo "npmAuthToken: $NODE_AUTH_TOKEN" >> .yarnrc.yml
        cp .yarnrc.yml /tmp/.yarnrc
        cat .yarnrc.yml
      env:
        NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

    - name: Setup yarn
      run: npm install -g yarn@2.4.3

    - run: yarn --version
    - run: yarn 
    - run: yarn run build
    - run: yarn run test

    - name: Bump version
      run: |
        echo $INPUT_REVISION
        npm version --no-git-tag-version $INPUT_REVISION
        PACKAGE_VERSION=$(cat package.json \
        | grep version \
        | head -1 \
        | awk -F: '{ print $2 }' \
        | sed 's/[",]//g' | cut -c2- )
        cat << EOF > CHANGELOG-new.md
        # Next version

        # $PACKAGE_VERSION

        EOF
        tail --lines=+3 CHANGELOG.md >>CHANGELOG-new.md
        mv CHANGELOG-new.md CHANGELOG.md
      env:
        INPUT_REVISION: ${{ inputs.revision }}

    - name: Publish
      run: |
        if [ "$INPUT_REVISION" = "prerelease" ]; then
          tag="next"
        
        else
          tag="latest"
        fi
        yarn npm publish --access public --tag $tag
      env:
        INPUT_REVISION: ${{ inputs.revision }}

    - name: setup git
      run: |
        echo "INPUT_COMMIT_USER_NAME: ${INPUT_COMMIT_USER_NAME}";
        git config --global user.name  "${INPUT_COMMIT_USER_NAME}";
        echo "INPUT_COMMIT_USER_EMAIL: ${INPUT_COMMIT_USER_EMAIL}";
        git config --global user.email ${INPUT_COMMIT_USER_EMAIL}

      env:
        INPUT_COMMIT_USER_NAME:  github-actions-bot
        INPUT_COMMIT_USER_EMAIL: github-actions-bot@users.noreply.github.com

    - name: git version
      run: |
        git status
        PACKAGE_VERSION=$(cat package.json \
        | grep version \
        | head -1 \
        | awk -F: '{ print $2 }' \
        | sed 's/[",]//g' | cut -c2- )
        echo "version: $PACKAGE_VERSION"
        git switch -c "release/v$PACKAGE_VERSION"
        git add package.json yarn.lock CHANGELOG.md
        git commit -m "$PACKAGE_VERSION [$USER]"
        git tag -m "v$PACKAGE_VERSION" -s "v$PACKAGE_VERSION"
        git push --set-upstream origin release/v$PACKAGE_VERSION
        git push --tags

        export RELEASE_NOTES=`sed -n "/^# $PACKAGE_VERSION/,/^#/p" CHANGELOG.md | grep -v "^#" | sed -e :a -e '/./,$!d;/^\n*$/{$d;N;};/\n$/ba'`
        echo $RELEASE_NOTES
        gh release create "v$PACKAGE_VERSION" --title "v$PACKAGE_VERSION" --notes "$RELEASE_NOTES"
        gh pr create --title "v$PACKAGE_VERSION" --body "" # --label "release" # --reviewer "mangrovedao/all-devs"
        gh pr merge --squash --delete-branch --auto
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER: ${{ github.actor }}
